name: Premake5 build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Run premake '5.0.0-beta1'
        uses: eariassoto/setup-premake@v1
        with:
          version: '5.0.0-beta1'
          action: 'gmake'
          options: '--cc=clang'
